name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variable
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "VERSION=${{ vars.VERSION }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "VERSION=${{ vars.VERSION }}-dev" >> $GITHUB_ENV
          fi

      - name: Read environment variables
        run:  echo "Environment $ENVIRONMENT, Version $VERSION"

      - name: Set version variable
        run: echo "VERSION=${{vars.VERSION}}" >> $GITHUB_ENV

      - name: Read version variable
        run:  echo $VERSION
         
      - name: Mostrar variables de entorno
        run: env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{vars.REPO_NAME}}:v${{vars.VERSION}} .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{vars.REPO_NAME}}:v${{vars.VERSION}} xy1207/${{vars.REPO_NAME}}:v${{vars.VERSION}}
          docker push xy1207/${{vars.REPO_NAME}}:v${{vars.VERSION}}